### PR TITLE
Change Login view

### PR DESCRIPTION
**Pull request by markusguenther**
The current login view of Gerrit is really minimalistic.
So this pull request will change that.

Because we are not able to change the markup it is a bit complicated. I used the library EQCSS to change parent node styles and because of some issues with new JS code I needed to load the JS library dynamically.

The old login gets new styles (using SASS) and because the markup of Gerrit is a old table layout I also added some changes via javascript.
Otherwise placeholders would not possible and the error message would be at another place.

When I create a new script tag then my docker instance with Gerrit crashes.

bildschirmfoto 2017-12-26 um 02 03 57-min

Resolves:  #15
Resolves:  #11

### CODE REVIEW

**Comment by StephenKing** [comment]
Those files need to be listed [here](https://github.com/TYPO3-cookbooks/site-reviewtypo3org/blob/master/attributes/theme.rb).

**Comment by markusguenther** [comment]
@StephenKing Hope that everything is ok... only tested my changes in the code.

**Comment by markusguenther** [comment]
Only one thing is left ... gulp needs to change the HTML templates to include the cached styles and javascript sources.

**Comment by markusguenther** [comment]
@StephenKing Ready for merge ;)

Should fit now, also added a few lines for the theming to the README.

**Comment by StephenKing** [comment]
Thanks for your nice work! Deployment worked fine (locally and in CI). Let's see what the users say ;-)

**Comment by markusguenther** [comment]
Thanks for using it :D 
Will see when I find some time for the menu.

**Comment by paladox** [comment]
You should upstream this :). (Leaving out the logo).

https://gerrit.googlesource.com/gerrit/+/refs/heads/master/resources/com/google/gerrit/httpd/auth/ldap/LoginForm.html

**Comment by sgrossberndt** [comment]
That would be nice and might additionally give the opportunity to adapt the HTML source too..

**Comment by markusguenther** [comment]
Yeah the markup is not that nice or better said HTML from ancient time. But will see if I find some time.

**Comment by hashar** [comment]
Thank you Typo3 team. @paladox added it to the Wikimedia Foundation Gerrit instance: https://gerrit.wikimedia.org/r/login/   Well done!

**Comment by paladox** [comment]
I have made wmf version not use the eqcss library :).

**Comment by paladox** [comment]
I presume the background image is licensed under apache 2.0? If so i can give a go at importing this into gerrit with credits going to @markusguenther (and also i will use the non eqcss version (wmf)). If you want i can import our version into type3 repo if you want?

**Comment by markusguenther** [comment]
@paladox followed the change in your gerrit a bit. Already saw that you changed classes in gerrit to get rid of the js library.

The image is under public CC from https://pixnio.com/nature-landscapes/lake/nature-reflection-lake-landscape-mountain-tree-water

**Comment by paladox** [comment]
Thanks. Hmm not so easy to impoprt due to it needing to know if a use uses a base url or not and not sure where to put the image in gerrit.

**Comment by paladox** [comment]
@markusguenther i will leave it to you to upload it if you want to upstream :).

Im not sure how to do it as it has javascript already and because we customised it, the logo carn't be used + background image will likly brake on base url's :).

**Comment by markusguenther** [comment]
@paladox You mean how to adjust the GWT templates of gerrit itself to achieve that login.

At the moment I have not that much time to make it, but I guess I would only change the styles and the markup in Gerrit and don't provide a image. Only a colored background. Then everybody can customize the background image with plain css.

Because I think many gerrit users will have their own.

**Comment by paladox** [comment]
@markusguenther ah thanks.

What colour would you choose?

(You seem to be a really great ui creator :))

**Comment by markusguenther** [comment]
Thanks but I am really now design guy. Normally I am a backend dev and only know some frontend stuff from the past. Also did some GWT in 2012 ... so maybe I find a proper way to handle this.

But don't know when I can upstream it.

**Pull request merged**
