### PR TITLE
Fix error related to new login UI

### PR DESCRIPTION
**Pull request by markusguenther**
I thank @paladox for reporting this and fixing the issue.
Just fired the gulp tool chain and removed a console.log().

Fixes: #20
Fixes: #22

### CODE REVIEW

**Comment by paladox** [comment]
Thanks :).

**Comment by markusguenther** [comment]
Your welcome and thank you. Was my mistake 😔

**Comment by markusguenther** [comment]
This is a fork of the PR #18 ... I am not a member and therefore I can not refactor PRs.

https://github.com/TYPO3-cookbooks/site-reviewtypo3org/pull/18

**Comment by markusguenther** [comment]
To make it easier for @StephenKing to deploy that I merged the changes of PR #18 and #19 now.
Hope this it is not a big deal for @paladox 

Thanks again for reporting.

**Comment by paladox** [comment]
Thanks :).

**Pull request merged**
